version: "2"

services:
  web:
    build:
      context: ./nginx
      # dockerfile: nginx.Dockerfile
    image: nginx-lb
    ports:
      - "80:80"
    networks:
      - mynetwork

  node1:
    build:
      context: ./node
      # dockerfile: node.Dockerfile
    image: node-lb
    environment:
      - MESSAGE="from node1"
    networks:
      - mynetwork

  node2:
    image: node-lb
    environment:
      - MESSAGE="from node2"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
