version: "2"

services:
  web:
    build:
      context: ./nginx
    image: nginx-lb
    ports:
      - "80:80"

  node1:
    build:
      context: ./node
    image: node-lb
    environment:
      - MESSAGE="from node1"

  node2:
    image: node-lb
    environment:
      - MESSAGE="from node2"
