version: "2"

services:
  web:
    build:
      context: ./nginx
    image: nginx-lb
    ports:
      - "80:80"
    # networks:
    #   - mynetwork

  node1:
    build:
      context: ./node
    image: node-lb
    environment:
      - MESSAGE="from node1"
    # networks:
    #   - mynetwork

  node2:
    image: node-lb
    environment:
      - MESSAGE="from node2"
#     networks:
#       - mynetwork

#   db:
#     image: mysql:5.7
#     environment:
#       - MYSQL_DATABASE=my-db
#       - MYSQL_USER=user
#       - MYSQL_PASSWORD=password
#       - MYSQL_ROOT_PASSWORD=root
#     volumes:
#       - ./db-data:/var/lib/mysql
#     ports:
#       - "3307:3306"
#     networks:
#       - mynetwork

# networks:
#   mynetwork:
#     driver: bridge
