version: "2"

services:
  web:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: nginx-lb
    ports:
      - "80:80"

  node1:
    build:
      context: .
      dockerfile: node.Dockerfile
    image: node-lb
    environment:
      - MESSAGE="from node1"
    ports:
      - "8081:3000"

  node2:
    # build:
    #   context: .
    #   dockerfile: node.Dockerfile
    image: node-lb
    environment:
      - MESSAGE="from node2"
    ports:
      - "8082:3000"
# networks:
#   mynetwork:
#     driver: bridge
